apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: msusers-ns
data:
  application.properties: |
    # COMMON 
    spring.application.name=Inventory
    server.port=9105
    # DB
    spring.datasource.url=jdbc:postgresql://postgres:5432/users_db
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.database=postgresql
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.sql.init.mode=always
    # LOGGING
    logging.level.org.springframework=INFO
    #Kafka
    spring.cloud.stream.kafka.binder.brokers=kafka-service
    spring.cloud.stream.kafka.binder.defaultBrokerPort=9092
    spring.cloud.stream.kafka.binder.autoCreateTopics=true
    spring.cloud.stream.bindings.itemok.destination=InventoryOK
    spring.cloud.stream.bindings.itemfail.destination=InventoryFail
    spring.cloud.stream.bindings.output.content-type=application/json
    spring.kafka.bootstrap-servers=kafka-service:9092
    
